# Generated by Django 5.2.6 on 2025-09-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Urgent'), (2, 'Important'), (3, 'Medium importance'), (4, 'Low importance'), (5, 'Optional')]),
        ),
    ]
