# Generated by Django 5.2.6 on 2025-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Task is waiting to be done'), ('Overdue', "Task wasn't done in time "), ('Done', 'Task was done in time')], default='Pending', max_length=10),
        ),
    ]
