# Generated by Django 5.2.6 on 2025-10-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.IntegerField(choices=[(1, 'None'), (2, '1 hour'), (3, '30 minutes'), (4, '10 minutes')], default=1),
        ),
    ]
