# Generated by Django 5.2.6 on 2025-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_task_failed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
