# Generated by Django 5.2.6 on 2025-10-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_celery_task_reminder_reminding'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='local_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
